kind: pipeline
type: docker
name: nestjs-ci-cd

steps:
  - name: install-and-test
    image: node:22-slim
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm install --prefer-offline
      - pnpm run test

  - name: deploy-to-vps
    image: appleboy/drone-ssh
    settings:
      host: drone.ahmadasgf.my.id
      username: ahmadasgf
      key:
        from_secret: SSH_KEY
      port: 22
      script:
        - cd ~/apps/shorten-link || mkdir -p ~/apps/shorten-link && cd ~/apps/shorten-link
        - |
          if [ ! -d ".git" ]; then
            git clone https://github.com/ahmaddassegaff/shorten-link .
          fi

        - git fetch origin
        - git reset --hard origin/main

        - export PNPM_HOME="/usr/local/share/pnpm"
        - export PATH="$PNPM_HOME:$PATH"
        - corepack enable
        - corepack prepare pnpm@latest --activate
        - pnpm install --prod --prefer-offline
        - pnpm run build
        - |
          if pm2 describe shorten-link > /dev/null; then
            pm2 reload shorten-link
          else
            pm2 start dist/main.js --name shorten-link
          fi

        - pm2 save

trigger:
  branch:
    - main
