services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app-nest
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - backend-net

networks:
  backend-net:
    external: true
